basePath: /api/v1
definitions:
  main.NotificationRequest:
    properties:
      message:
        type: string
      sendEmail:
        type: boolean
      type:
        type: string
      userEmail:
        type: string
    type: object
  services.NotificationCreateResponse:
    properties:
      _id:
        type: string
      message:
        type: string
      read:
        type: boolean
      type:
        type: string
      userEmail:
        type: string
    type: object
info:
  contact: {}
  title: Notification Management API documentation
  version: 1.0.0
paths:
  /api/v1/notification:
    post:
      consumes:
      - application/json
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/main.NotificationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Okay
          schema:
            $ref: '#/definitions/services.NotificationCreateResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create Notification
      tags:
      - Notification
swagger: "2.0"
