openapi: 3.0.0
servers:
  - description: The local dev server
    url: http://localhost:8080/taskgroup
info:
  description: "CRUD Operations for Tasks Group"
  version: "1.0.0"
  title: "Task Group API"
  contact:
    email: "choreo-help@wso2.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: "todo"
    description: "Sample todo application"
  - name: "demo"
    description: "This api is created for demo purposes"
paths:
  /taskgroup:
    get:
      summary: "returns task groups for a given user id"
      operationId: "getTasksGroupByUserId"
      description: |
        Give a list of task groups given the user Id. list will be sorted by last updated date.
      parameters:
        - in: "query"
          name: "userId"
          description: "User Id"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "list of tasks grousp belonging to the given user"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TaskGroup"
        "500":
          description: "internal error occurred"
    post:
      summary: "Create a Task Group"
      operationId: "createTaskGroup"
      description: "Create a task group with given details"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "Urgent and Important"
                userId:
                  type: string
                  example: "698d8383-28f1-4d2c-8179-e11a290e0910"
        description: "An example task group"
      responses:
        "201":
          description: "item created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskGroup"
        "400":
          description: "invalid input, object invalid"
        "500":
          description: "internal server error occurred"
  /taskgroup/{id}:
    get:
      summary: "Retrieve a task group by id"
      operationId: "getTaskGroupById"
      description: |
        Retrieve a task group by id.
      parameters:
        - name: id
          in: path
          description: "Task Group Id"
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        "200":
          description: "The task group with Id"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskGroup"

        "404":
          description: "Unable to find the task"
    put:
      summary: "Update a task group by id"
      operationId: "updateTaskGroupById"
      description: |
        Update a task Group by id.
      parameters:
        - name: id
          in: path
          description: "Task Group Id"
          required: true
          schema:
            type: integer
            minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "Urgent and Important"
        description: "An example task group"
      responses:
        "200":
          description: "The task group with Id"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskGroup"

        "404":
          description: "Unable to find the task group"
    delete:
      summary: "Delete a task group by id"
      operationId: "deleteTaskGroupById"
      description: |
        Delete a task group by id.
      parameters:
        - name: id
          in: path
          description: "Task Group Id"
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        "200":
          description: "The task group with Id"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskGroup"
        "404":
          description: "Unable to find the task group"
components:
  schemas:
    Task:
      type: object
      required:
        - id
        - title
        - taskGroupId
        - taskStatus
        - createdAt
        - updatedAt
      properties:
        id:
          type: integer
          minimum: 1
          example: 10
        title:
          type: string
          example: "Review monthly expenses"
        taskGroupId:
          type: integer
          minimum: 1
          example: 5
        taskStatus:
          type: string
          example: "Open"
        createdAt:
          type: string
          format: date-time
          example: "2022-10-12T15:56:12.171Z"
        updatedAt:
          type: string
          format: date-time
          example: "2022-10-12T15:56:12.171Z"
    TaskGroup:
      type: object
      required:
        - id
        - title
        - userId
        - createdAt
        - updatedAt
      properties:
        id:
          type: integer
          minimum: 1
          example: 10
        title:
          type: string
          example: "Urgent and important tasks"
        userId:
          type: string
          example: "ea69ddda-c44f-4ba5-a701-fda8a6c1ff42"
        createdAt:
          type: string
          format: date-time
          example: "2022-10-12T15:56:12.171Z"
        updatedAt:
          type: string
          format: date-time
          example: "2022-10-12T15:56:12.171Z"
    TaskStatus:
      type: object
      required:
        - id
        - name
        - userId
        - createdAt
        - updatedAt
      properties:
        id:
          type: integer
          minimum: 1
          example: 10
        name:
          type: string
          example: "InProgress"
        userId:
          type: string
          example: "ea69ddda-c44f-4ba5-a701-fda8a6c1ff42"
        createdAt:
          type: string
          format: date-time
          example: "2022-10-12T15:56:12.171Z"
        updatedAt:
          type: string
          format: date-time
          example: "2022-10-12T15:56:12.171Z"
